name: Feature request
description: Suggest an idea or improvement.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Got an idea? We'd love to hear it. Keep it simple.
  - type: dropdown
    id: author
    attributes:
      label: Who's filing this?
      options:
        - I'm a human
        - I'm an AI agent
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What do you want?
      description: Describe the feature or improvement you'd like to see.
      placeholder: It would be nice if the WebUI showed timestamps in relative format (e.g. "2 min ago").
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why?
      description: What problem does this solve? Why does it matter?
      placeholder: Absolute timestamps are harder to parse at a glance when watching a live conversation.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any other approaches you've considered? Optional.
      placeholder: Could also add a toggle between relative and absolute timestamps.
